packages:
  - "docs/"
  - "playground/"
  - "./"
onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@tsparticles/engine'
  - "better-sqlite3"
  - esbuild
  - "sharp"
  - unrs-resolver
  - vue-demi
  - workerd
