packages:
  - "docs/"
  - "playground/"
  - "./"
shamefullyHoist: true
strictPeerDependencies: false
shellEmulator: true
packageConfigs:
  nuxthub-docs:
    shamefullyHoist: true
  '@nuxthub/core':
    shamefullyHoist: true
    strictPeerDependencies: false
    shellEmulator: true
allowBuilds:
  '@parcel/watcher': true
  '@tsparticles/engine': true
  better-sqlite3: true
  esbuild: true
  sharp: true
  unrs-resolver: true
  vue-demi: true
  workerd: true
