title: Database
icon: i-lucide-database
navigation.title: Database
seo.title: Nuxt SQL Database
description: Access a SQL database with Drizzle ORM in Nuxt to store and retrieve relational data with full type-safety.
