title: 'Changelog'
description: 'Follow the latest updates and improvements of NuxtHub.'
icon: i-lucide-megaphone
hero:
  title: 'Changelog'
  description: 'Follow the latest updates and improvements of NuxtHub.'
  align: center
  links:
    - label: '@nuxt_hub'
      icon: i-simple-icons-x
      color: neutral
      variant: outline
      size: sm
      to: https://x.com/nuxt_hub
      target: _blank
    - label: 'NuxtHub'
      icon: i-simple-icons-linkedin
      color: neutral
      variant: outline
      size: sm
      to: https://www.linkedin.com/showcase/nuxthub/
      target: _blank
    - label: 'Changelog RSS'
      icon: 'i-simple-icons-rss'
      to: '/changelog/rss.xml'
      color: neutral
      variant: outline
      size: sm
      target: _blank
