<script setup lang="ts">
import { ref, computed } from 'vue'
import { useFetch } from '#app'
import { useToast } from '@nuxt/ui/runtime/composables/useToast'
import { AlertDialogRoot, AlertDialogPortal, AlertDialogOverlay, AlertDialogContent, AlertDialogTitle, AlertDialogDescription, AlertDialogAction, AlertDialogCancel } from 'reka-ui'
import { useApiBase } from '~/composables/useApiBase'

interface CacheItem { key: string, value: unknown }

const toast = useToast()
const apiBase = useApiBase()
const search = ref('')
const viewOpen = ref(false)
const deleteOpen = ref(false)
const clearOpen = ref(false)
const selectedItem = ref<CacheItem | null>(null)

const { data, status, refresh } = await useFetch<CacheItem[]>(
  () => `${apiBase.value}/_hub/devtools/cache`,
  { onResponseError: () => toast.add({ title: 'Failed to fetch cache', color: 'error' }) }
)

const loading = computed(() => status.value === 'pending')
const items = computed(() => data.value ?? [])

const filteredItems = computed(() => {
  if (!search.value) return items.value
  return items.value.filter(i => i.key.toLowerCase().includes(search.value.toLowerCase()))
})

const groupedItems = computed(() => {
  const groups: Record<string, CacheItem[]> = {}
  for (const item of filteredItems.value) {
    const prefix = item.key.split(':').slice(0, 2).join(':') || 'other'
    if (!groups[prefix]) groups[prefix] = []
    groups[prefix].push(item)
  }
  return Object.entries(groups).sort(([a], [b]) => a.localeCompare(b))
})

function formatValue(val: unknown): string {
  if (val === null) return 'null'
  if (val === undefined) return 'undefined'
  if (typeof val === 'object') {
    const str = JSON.stringify(val)
    return str.length > 60 ? str.slice(0, 60) + '...' : str
  }
  const str = String(val)
  return str.length > 60 ? str.slice(0, 60) + '...' : str
}

function openView(item: CacheItem) {
  selectedItem.value = item
  viewOpen.value = true
}

function openDelete(item: CacheItem) {
  selectedItem.value = item
  deleteOpen.value = true
}

async function confirmDelete() {
  if (!selectedItem.value) return
  try {
    await $fetch(`${apiBase.value}/_hub/devtools/cache/${encodeURIComponent(selectedItem.value.key)}`, { method: 'DELETE' })
    toast.add({ title: 'Deleted', color: 'success' })
    deleteOpen.value = false
    await refresh()
  } catch {
    toast.add({ title: 'Failed to delete', color: 'error' })
  }
}

async function confirmClear() {
  try {
    await $fetch(`${apiBase.value}/_hub/devtools/cache/clear`, { method: 'POST', body: { confirm: 'CLEAR_ALL' } })
    toast.add({ title: 'Cleared all cache', color: 'success' })
    clearOpen.value = false
    await refresh()
  } catch {
    toast.add({ title: 'Failed to clear', color: 'error' })
  }
}
</script>

<template>
  <div>
    <!-- Header -->
    <div class="flex items-center justify-between mb-4">
      <div class="flex items-center gap-2">
        <UBadge
          color="neutral"
          variant="subtle"
        >
          {{ items.length }} entries
        </UBadge>
      </div>
      <div class="flex gap-2">
        <UButton
          icon="i-lucide-rotate-cw"
          color="neutral"
          variant="ghost"
          :loading
          @click="refresh"
        />
        <UButton
          icon="i-lucide-trash-2"
          color="error"
          variant="soft"
          :disabled="!items.length"
          @click="clearOpen = true"
        >
          Clear All
        </UButton>
      </div>
    </div>

    <!-- Search -->
    <UInput
      v-model="search"
      placeholder="Search cache keys..."
      icon="i-lucide-search"
      class="mb-4 max-w-xs"
    />

    <!-- Loading State -->
    <div
      v-if="loading"
      class="space-y-2"
    >
      <USkeleton
        v-for="n in 5"
        :key="n"
        class="h-12 w-full"
      />
    </div>

    <!-- Empty State -->
    <UEmpty
      v-else-if="!filteredItems.length"
      icon="i-lucide-database"
      title="No cache entries"
      description="Cache entries are auto-generated by Nitro handlers and functions"
    />

    <!-- Grouped Table -->
    <div
      v-else
      class="space-y-4"
    >
      <div
        v-for="[group, groupItems] in groupedItems"
        :key="group"
        class="border border-default rounded-lg overflow-hidden"
      >
        <div class="bg-elevated px-4 py-2 border-b border-default">
          <span class="font-medium text-sm text-highlighted">{{ group }}</span>
          <span class="text-xs text-muted ml-2">({{ groupItems.length }})</span>
        </div>
        <table class="w-full text-sm">
          <tbody>
            <tr
              v-for="item in groupItems"
              :key="item.key"
              class="border-t border-default first:border-t-0 hover:bg-accented cursor-pointer transition-colors"
              @click="openView(item)"
            >
              <td class="px-4 py-2.5 font-mono text-xs text-highlighted truncate max-w-md">
                {{ item.key.replace(group + ':', '') }}
              </td>
              <td class="px-4 py-2.5 font-mono text-xs text-muted truncate max-w-sm">
                {{ formatValue(item.value) }}
              </td>
              <td class="px-2 py-2.5 w-16">
                <div
                  class="flex gap-0.5 justify-end"
                  @click.stop
                >
                  <UButton
                    size="xs"
                    color="error"
                    variant="ghost"
                    icon="i-lucide-trash-2"
                    @click="openDelete(item)"
                  />
                </div>
              </td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>

    <!-- View Modal -->
    <UModal
      v-model:open="viewOpen"
      title="Cache Entry"
      :description="selectedItem?.key"
      :transition="false"
      class="sm:max-w-xl"
    >
      <template #body>
        <pre class="bg-elevated rounded-lg p-4 text-xs font-mono overflow-auto max-h-96">{{ selectedItem?.value ? JSON.stringify(selectedItem.value, null, 2) : 'null' }}</pre>
      </template>
      <template #footer>
        <UButton
          color="neutral"
          variant="ghost"
          @click="viewOpen = false"
        >
          Close
        </UButton>
        <UButton
          v-if="selectedItem"
          color="error"
          variant="soft"
          @click="viewOpen = false; openDelete(selectedItem)"
        >
          Delete
        </UButton>
      </template>
    </UModal>

    <!-- Delete AlertDialog -->
    <AlertDialogRoot v-model:open="deleteOpen">
      <AlertDialogPortal>
        <AlertDialogOverlay class="fixed inset-0 bg-black/50 z-50" />
        <AlertDialogContent class="fixed top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 bg-elevated rounded-lg p-6 max-w-md z-50 shadow-lg">
          <AlertDialogTitle class="text-lg font-semibold text-highlighted">
            Delete Cache Entry?
          </AlertDialogTitle>
          <AlertDialogDescription class="text-muted mt-2">
            Are you sure you want to delete <code class="font-mono bg-accented px-1.5 py-0.5 rounded text-sm text-highlighted break-all">{{ selectedItem?.key }}</code>?
          </AlertDialogDescription>
          <div class="flex justify-end gap-2 mt-4">
            <AlertDialogCancel as-child>
              <UButton color="neutral" variant="ghost">
                Cancel
              </UButton>
            </AlertDialogCancel>
            <AlertDialogAction as-child>
              <UButton color="error" @click="confirmDelete">
                Delete
              </UButton>
            </AlertDialogAction>
          </div>
        </AlertDialogContent>
      </AlertDialogPortal>
    </AlertDialogRoot>

    <!-- Clear All AlertDialog -->
    <AlertDialogRoot v-model:open="clearOpen">
      <AlertDialogPortal>
        <AlertDialogOverlay class="fixed inset-0 bg-black/50 z-50" />
        <AlertDialogContent class="fixed top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 bg-elevated rounded-lg p-6 max-w-md z-50 shadow-lg">
          <AlertDialogTitle class="text-lg font-semibold text-highlighted">
            Clear All Cache?
          </AlertDialogTitle>
          <AlertDialogDescription class="text-muted mt-2">
            This will delete <strong class="text-highlighted">ALL {{ items.length }} cache entries</strong>. This action cannot be undone.
          </AlertDialogDescription>
          <div class="flex justify-end gap-2 mt-4">
            <AlertDialogCancel as-child>
              <UButton color="neutral" variant="ghost">
                Cancel
              </UButton>
            </AlertDialogCancel>
            <AlertDialogAction as-child>
              <UButton color="error" @click="confirmClear">
                Clear All
              </UButton>
            </AlertDialogAction>
          </div>
        </AlertDialogContent>
      </AlertDialogPortal>
    </AlertDialogRoot>
  </div>
</template>
